### ISSUE TITLE
Dir3caib 1.0.8 no funciona

### ISSUE THREAD

**Issue by canosis** [GovernIB/dir3caib#1]
Hola. Acabo de instalar la version de dir3caib 1.0.8 y al arrancar me sigue apareciendo que es la version 1.0.7. Ademas, siguiendo las instrucciones:

6. Accedir a l’aplicació i al menú sincronització púlsar en primer lloc l’opció Sincronitzar
directori.

Al hacer esto, la pantalla se queda en blanco y no hace nada. ¿Lo podeis solucionar?

Gracias

**Comment by earrivi-fundaciobit** [comment]
Buenas,

Has configurado las rutas a los WS de dir3 correctamente? Tienes acceso a la redSara?

Podrías enviarnos el log del jboss.

Desde que Administración nos escribes?

Gracias,

Saludos,

**Comment by canosis** [comment]
Si, tengo acceso a redSara.
La rutas de los WS apuntan a correctamente a dir3ws ya que anteriormente teniamos instalada la version de regweb 3.0.9 y dir3caib 1.0.7 y funcionanban correctamente, pero he intentado actualizar al nuevo regweb 3.1 y dir3caib 1.0.8, y ahora no va.

El log de del jboss solo dice esto:
2019-02-18 08:27:35,120 INFO  [es.caib.dir3caib.back.security.AuthenticationSuccessListener] (http-0.0.0.0-8080-5)  =================================================================
2019-02-18 08:27:35,121 INFO  [es.caib.dir3caib.back.security.AuthenticationSuccessListener] (http-0.0.0.0-8080-5)  ============ Login Usuari: admin
2019-02-18 08:27:35,121 INFO  [es.caib.dir3caib.back.security.AuthenticationSuccessListener] (http-0.0.0.0-8080-5) Rol SEYCON : DIR_ADMIN

**Comment by earrivi-fundaciobit** [comment]
Hola,

Acabo de probar el ear que viene en la [release publicada](https://github.com/GovernIB/dir3caib/releases/download/dir3caib-1.0.8/release-dir3caib-1.0.8.zip) y el funcionamiento es correcto, conecta con los WS de DIR3 y se inicia la sincronización.

Por otra parte, cuando comentas que al arrancar aún te sigue apareciendo al versión 1.0.7 de dir3caib, a que te refieres?

Saludos.

**Comment by canosis** [comment]
Me refiero que despues de seguir todas las instrucciones del manual (incluido copiar el ear en el directorio correspondiende), cuando abro el dir3caib me aparece esto:

![image](https://user-images.githubusercontent.com/26299785/52943759-231c7f00-336e-11e9-9811-677c958a6168.png)

**Comment by canosis** [comment]
Tras actualizar regweb 3.0.9 a 3.1 y dir3caib 1.0.7 a 1.0.8, esto es lo que me ocurre:

La pantalla del dir3caib muestra que es la version 1.0.7, como se puede ver en la imagen anterior. Dir3caib sincroniza bien al pulsar sobre "sincronizar catalogo", pero la pantalla se queda en blanco al pulsar sobre "sincronizar directorio".

Desde regweb 3.1 sincroniza bien contra el catalogo de dir3caib.

¿Como puedo solucionar el problema de "sincronizar directorio"?

**Comment by earrivi-fundaciobit** [comment]
El mensaje que te aparece es normal, porque supongo que has eliminado todo el contenido de la bbdd y la aplicación espera la sincronización inicial.

Lo primero es solucionar el problema con la versión de dir3caib, porque parece que no se esté desplegando el ear de la versión 1.0.8.

Me podrías hacer llegar el ear que estás utilizando a otae@fundaciobit.org

Gracias,

Saludos.

**Comment by canosis** [comment]
Te he mandado el fichero ear.

**Comment by earrivi-fundaciobit** [comment]
Hola,

No ha llegado nada.

Escríbeme a earrivi@fundaciobit.org y lo solucionamos.

Saludos.

**Comment by canosis** [comment]
OK. Ya te lo he mandado desde una cuenta de ticmallorca

**Comment by earrivi-fundaciobit** [comment]
Por temas de restricción de correo es posible que no entre, ¿puedes enviármelo mediante un servicio de almacenamiento, ftp o similar?
