### ISSUE TITLE
Retornar la versió a UnitatRest als serveis REST

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/dir3caib#58]
Als métodes del serveis REST que retornen un tipus UnitatRest, s'ha d'afegir que també retorni la versió de la unitat que es consultada.

**Comment by jagarcia-fundaciobit** [comment]
S'ha afegit el nou camp al tipus UnitatRest i s'ha actualitzat la documentació del manual de Webservices.

**Comment by jsastre-dgtic** [comment]
el pdf és buit...

**Comment by jagarcia-fundaciobit** [comment]
He regenerat el document en PDF que havia generat malament per error i ja està pujat de nou al Github.
