### ISSUE TITLE
Bug: Caida de dir3caib por demasiados ficheros abiertos

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/dir3caib#65]
A veces dir3caib cae dando el siguiente error:

[errordir3caib.txt](https://github.com/GovernIB/dir3caib/files/10940965/errordir3caib.txt)

**Comment by jagarcia-fundaciobit** [comment]
Hemos revisado los logs de producción tanto de Dir3Caib como de Seycon y hemos visto que a las 00:00h, hay un gran número de peticiones de Regweb hacia Dir3Caib.  

Por lo que hemos visto con Eduardo, a las 00:00, Regweb recibe un elevado número de peticiones para procesar registros SIR seguramente debido a tareas automatizadas que se ejecutan a esa hora. 

De momento, parece que se ha solucionado el problema aumentando el límite de descriptores de fichero que viene por defecto en el sistema operativo y no ha vuelto a dar problemas.
