### ISSUE TITLE
Nou mètode rest que donat un codi dir3 retorni el codi dir3 vigent darrer

### ISSUE THREAD

**Issue by mgonzalez-fundaciobit** [GovernIB/dir3caib#66]
Els codis dir3 d'una unitat poden canviar per canvis d'estructura tipo divisions i fusions.
Per tant, es vol que donat un codi dir3 qualsevol, ens retorni el codi dir3 actual que li correspon.

**Comment by jagarcia-fundaciobit** [comment]
S'ha creat un nou mètode a l'API REST accessible des de la url API_REST/unidades/historico. 

Aquest mètode ens retorna un objecte de tipus ObjetoDirectorioExtendido compost per un subconjunt de dades format per: codiDir3, denominació, denominació cooficial i estat. 

Si la unitat passada per paràmetre està extingida: el métode retorna la unitat vigent. En cas contrari, retorna la informació de la unitat que s'ha passat per paràmetre que està vigent. 

![image](https://github.com/GovernIB/dir3caib/assets/70194276/11cc75c9-3356-4f0b-8ef4-edbd9ba8ec21)
