### ISSUE TITLE
Error al intentar añadir al pom la version 1.1.0 o 1.1.1

### ISSUE THREAD

**Issue by d-hernandez00** [GovernIB/dir3caib#82]
Al intentar añadir una versión superior a la 1.0.15 en el pom se muestra un error de maven

![image](https://github.com/GovernIB/dir3caib/assets/157024764/6e8fbe58-b26c-4a2f-ac0f-05e1e348a80a)

**Comment by mgonzalez-fundaciobit** [comment]
Se ha hecho el deploy de la versión 1.1.0.
